events {
    worker_connections 1024;
}

http {
    upstream auth  { server auth-service:8081; }
    upstream docs  { server document-service:8082; }
    upstream notif { server notification-service:8083; }

    server {
        listen 80;

        # Chuyển tiếp JWT xuống service
        proxy_set_header Authorization $http_authorization;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        location /api/auth/ {
            proxy_pass http://auth/;
        }
        location /api/documents/ {
            proxy_pass http://docs/;
        }
        location /api/notifications/ {
            proxy_pass http://notif/;
        }
        location /uploads/ {
            alias /app/uploads/;
        }
    }
}